// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "PROJECT-III/domain"

	mock "github.com/stretchr/testify/mock"
)

// AdminData is an autogenerated mock type for the AdminData type
type AdminData struct {
	mock.Mock
}

// GetHistoryData provides a mock function with given fields:
func (_m *AdminData) GetHistoryData() []domain.Clothes {
	ret := _m.Called()

	var r0 []domain.Clothes
	if rf, ok := ret.Get(0).(func() []domain.Clothes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Clothes)
		}
	}

	return r0
}

type mockConstructorTestingTNewAdminData interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminData creates a new instance of AdminData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminData(t mockConstructorTestingTNewAdminData) *AdminData {
	mock := &AdminData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
