// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "PROJECT-III/domain"

	mock "github.com/stretchr/testify/mock"
)

// AdminUseCase is an autogenerated mock type for the AdminUseCase type
type AdminUseCase struct {
	mock.Mock
}

// CreateProducts provides a mock function with given fields: data
func (_m *AdminUseCase) CreateProducts(data domain.Clothes) {
	_m.Called(data)
}

// GetHistory provides a mock function with given fields: _a0, _a1
func (_m *AdminUseCase) GetHistory(_a0 []domain.Clothes, _a1 int) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewAdminUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminUseCase creates a new instance of AdminUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminUseCase(t mockConstructorTestingTNewAdminUseCase) *AdminUseCase {
	mock := &AdminUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
