services:
  mysqlData:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    
    ports:
      - 3307:3306


  project3app:
    image: red95f1/project3play
    environment:
      DBusername: "root"
      DBpassword: "asd12345"
      DBhost: "localhost"
      DBport: 3306
      DBname: "redb"
      SECRET: "pr0j3ct"
      SERVERPORT: 8080
    restart: always
    ports:
      - 8000:8080