name: Deploy to aws
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd PROJECT-III
            cd PROJECT-III
            git pull origin main
            docker stop containerProject3
            docker rm containerProject3
            docker rmi project3-api
            docker build -t project3-api:latest .
            docker run -d -p 80:8080 --name containerProject3 -e DBname=${{ secrets.DBNAME }} -e DBusername=${{ secrets.DBUSERNAME }} -e DBpassword=${{ secrets.DBPASSWORD }} -e DBhost=${{ secrets.DBHOST }} -e DBport=${{ secrets.DBPORT }} -e SECRET=${{ secrets.SECRET }} -e SERVERPORT=${{ secrets.SERVERPORT }} -e S3_KEY = ${{ secrets.S3_KEY }} -e S3_SECRET=${{ secrets.S3_SECRET }} -e S3_REGION=${{ secrets.S3_REGION }} project3-api:latest
